/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class terry_practice_jni_NativeTest */

#ifndef _Included_terry_practice_jni_NativeTest
#define _Included_terry_practice_jni_NativeTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     terry_practice_jni_NativeTest
 * Method:    test
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_terry_practice_jni_NativeTest_test
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
